#!/usr/bin/env bash
# CaeliCode WSL — Windows proxy detection
# Reads proxy settings from Windows and writes them to /etc/profile.d/caelicode-proxy.sh
# so all login shells inherit the correct HTTP_PROXY/HTTPS_PROXY/NO_PROXY.
#
# Also merges Windows root CA certificates into the Linux trust store for
# environments using MITM inspection (Zscaler, Netskope, etc.).
#
# Invoked once per boot by caelicode-runtime-init (gated on
# proxy.detect_enabled in /etc/caelicode/config.yaml), or manually:
#   sudo /opt/caelicode/current/scripts/proxy-detect.sh

set -uo pipefail

PROXY_ENV_FILE="/etc/profile.d/caelicode-proxy.sh"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

log() { echo "[caelicode-proxy] $*"; }

# ── Proxy Detection ─────────────────────────────────────────────────
# netsh output looks like ONE of:
#     Direct access (no proxy server).
# or:
#     Proxy Server(s) :  proxy.corp.example.com:8080
#     Bypass List     :  *.corp.example.com;<local>
#
# Parsing rules learned the hard way:
#  - match the LABEL case-sensitively and anchored, otherwise the
#    "no proxy server" line matches a case-insensitive grep and the
#    no-proxy case writes a garbage proxy system-wide;
#  - strip only the FIRST "label :" prefix — a greedy .*: eats through
#    the colon inside host:port and leaves only the port behind.
detect_windows_proxy() {
    local proxy_output
    proxy_output="$(/mnt/c/windows/system32/netsh.exe winhttp show proxy 2>/dev/null | tr -d '\r' || true)"

    local proxy_server
    proxy_server="$(printf '%s\n' "$proxy_output" \
        | grep -E '^[[:space:]]*Proxy Server' | head -1 \
        | sed -E 's/^[^:]*:[[:space:]]*//' | tr -d ' ')"

    if [ -n "$proxy_server" ]; then
        local bypass_list
        bypass_list="$(printf '%s\n' "$proxy_output" \
            | grep -E '^[[:space:]]*Bypass List' | head -1 \
            | sed -E 's/^[^:]*:[[:space:]]*//' | tr -d ' ')"
        [ "$bypass_list" = "(none)" ] && bypass_list=""
        printf '%s\n%s\n' "$proxy_server" "$bypass_list"
        return 0
    fi
    return 1
}

# Reduce a WinHTTP proxy value to a single host:port.
# Handles both "host:port" and "http=host:port;https=host2:port2" forms.
select_proxy_endpoint() {
    local raw="$1"
    if [[ "$raw" == *"="* ]]; then
        local part
        for scheme in https http; do
            part="$(printf '%s\n' "$raw" | tr ';' '\n' | grep -E "^${scheme}=" | head -1 | cut -d= -f2-)"
            if [ -n "$part" ]; then printf '%s' "$part"; return 0; fi
        done
        return 1
    fi
    printf '%s' "$raw"
}

# The value lands in a root-owned file sourced by every login shell:
# accept only a strict host[:port] charset so no shell metacharacters
# can ever reach that file.
valid_endpoint() { [[ "$1" =~ ^[A-Za-z0-9._-]+(:[0-9]{1,5})?$ ]]; }

write_proxy_env() {
    local proxy="$1"
    local bypass="${2:-}"
    [ -n "$bypass" ] || bypass="localhost,127.0.0.1,::1"
    # Normalize the Windows semicolon-separated bypass list, then apply
    # the same strict charset rule as the proxy endpoint. <> appears in
    # the literal "<local>" token Windows uses for local addresses.
    bypass="$(printf '%s' "$bypass" | tr ';' ',')"
    local bypass_re='^[A-Za-z0-9.,*:_<>-]+$'
    if ! [[ "$bypass" =~ $bypass_re ]]; then
        log "Ignoring malformed bypass list; using defaults"
        bypass="localhost,127.0.0.1,::1"
    fi

    cat > "$PROXY_ENV_FILE" <<PROXYEOF
# Auto-generated by CaeliCode proxy detection
# Re-run: sudo /opt/caelicode/current/scripts/proxy-detect.sh
export HTTP_PROXY="http://${proxy}"
export HTTPS_PROXY="http://${proxy}"
export http_proxy="http://${proxy}"
export https_proxy="http://${proxy}"
export NO_PROXY="${bypass}"
export no_proxy="${bypass}"
PROXYEOF
    chmod 644 "$PROXY_ENV_FILE"
    log "Proxy configured: ${proxy} (bypass: ${bypass})"
}

clear_proxy_env() {
    cat > "$PROXY_ENV_FILE" <<'PROXYEOF'
# No proxy detected by CaeliCode
# Re-run: sudo /opt/caelicode/current/scripts/proxy-detect.sh
unset HTTP_PROXY HTTPS_PROXY http_proxy https_proxy NO_PROXY no_proxy 2>/dev/null || true
PROXYEOF
    chmod 644 "$PROXY_ENV_FILE"
    log "No proxy detected — environment cleared"
}

# ── CA Certificate Merge ─────────────────────────────────────────────
merge_windows_certs() {
    local linux_cert_dir="/usr/local/share/ca-certificates/caelicode"

    # Export Windows root certs via PowerShell
    local cert_pem
    # shellcheck disable=SC2016  # Single quotes intentional: PowerShell Cert:\ path
    cert_pem="$(/mnt/c/windows/system32/windowspowershell/v1.0/powershell.exe \
        -NoProfile -NonInteractive -Command \
        'Get-ChildItem -Path Cert:\LocalMachine\Root | ForEach-Object { [System.Convert]::ToBase64String($_.RawData) }' \
        2>/dev/null | tr -d '\r' || true)"

    if [ -n "$cert_pem" ]; then
        mkdir -p "$linux_cert_dir"
        local cert_file="${linux_cert_dir}/windows-root-cas.crt"
        : > "$cert_file"
        local count=0
        while IFS= read -r b64; do
            [ -z "$b64" ] && continue
            # Only strict base64 lines — anything else is PowerShell noise.
            [[ "$b64" =~ ^[A-Za-z0-9+/=]+$ ]] || continue
            {
                echo "-----BEGIN CERTIFICATE-----"
                echo "$b64" | fold -w 64
                echo "-----END CERTIFICATE-----"
            } >> "$cert_file"
            count=$((count + 1))
        done <<< "$cert_pem"
        update-ca-certificates >/dev/null 2>&1 || true
        log "Merged ${count} Windows root CA certificates into Linux trust store"
    else
        log "No Windows root certificates detected"
    fi
}

# ── Main ─────────────────────────────────────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
    echo "[caelicode-proxy] ERROR: must run as root (writes ${PROXY_ENV_FILE})" >&2
    exit 1
fi

PROXY_OUTPUT="$(detect_windows_proxy || true)"

if [ -n "$PROXY_OUTPUT" ]; then
    RAW_PROXY="$(printf '%s\n' "$PROXY_OUTPUT" | head -1)"
    BYPASS="$(printf '%s\n' "$PROXY_OUTPUT" | tail -1)"
    PROXY="$(select_proxy_endpoint "$RAW_PROXY" || true)"
    if [ -n "$PROXY" ] && valid_endpoint "$PROXY"; then
        write_proxy_env "$PROXY" "$BYPASS"
    else
        log "Detected proxy value looks invalid ('${RAW_PROXY}') — leaving environment unchanged"
    fi
else
    clear_proxy_env
fi

# Merge CA certs if configured
CFG="${SCRIPT_DIR}/caelicode-config"
if [ -x "$CFG" ] && "$CFG" is-enabled proxy.merge_ca_certs false; then
    merge_windows_certs
fi
