#!/usr/bin/env bash
# CaeliCode WSL — Windows proxy detection
# Reads proxy settings from Windows and writes them to /etc/profile.d/caelicode-proxy.sh
# so all login shells inherit the correct HTTP_PROXY/HTTPS_PROXY/NO_PROXY.
#
# Also merges Windows root CA certificates into the Linux trust store for
# environments using MITM inspection (Zscaler, Netskope, etc.).

set -uo pipefail

PROXY_ENV_FILE="/etc/profile.d/caelicode-proxy.sh"

log() { echo "[caelicode-proxy] $*"; }

# ── Proxy Detection ─────────────────────────────────────────────────
detect_windows_proxy() {
    local proxy_output
    proxy_output="$(/mnt/c/windows/system32/netsh.exe winhttp show proxy 2>/dev/null | tr -d '\r' || true)"

    local proxy_server
    proxy_server="$(echo "$proxy_output" | grep -i "Proxy Server" | sed 's/.*: *//' | tr -d ' ')"

    if [ -n "$proxy_server" ] && [ "$proxy_server" != "(none)" ]; then
        local bypass_list
        bypass_list="$(echo "$proxy_output" | grep -i "Bypass List" | sed 's/.*: *//' | tr -d ' ')"
        # Output proxy and bypass separated by a newline
        echo "$proxy_server"
        echo "${bypass_list:-}"
        return 0
    fi
    return 1
}

write_proxy_env() {
    local proxy="$1"
    local bypass="${2:-localhost,127.0.0.1,::1}"

    cat > "$PROXY_ENV_FILE" <<PROXYEOF
# Auto-generated by CaeliCode proxy detection
# Re-run: sudo /opt/caelicode/scripts/proxy-detect.sh
export HTTP_PROXY="http://${proxy}"
export HTTPS_PROXY="http://${proxy}"
export http_proxy="http://${proxy}"
export https_proxy="http://${proxy}"
export NO_PROXY="${bypass}"
export no_proxy="${bypass}"
PROXYEOF
    chmod 644 "$PROXY_ENV_FILE"
    log "Proxy configured: ${proxy} (bypass: ${bypass})"
}

clear_proxy_env() {
    cat > "$PROXY_ENV_FILE" <<'PROXYEOF'
# No proxy detected by CaeliCode
# Re-run: sudo /opt/caelicode/scripts/proxy-detect.sh
unset HTTP_PROXY HTTPS_PROXY http_proxy https_proxy NO_PROXY no_proxy 2>/dev/null || true
PROXYEOF
    chmod 644 "$PROXY_ENV_FILE"
    log "No proxy detected — environment cleared"
}

# ── CA Certificate Merge ─────────────────────────────────────────────
merge_windows_certs() {
    local linux_cert_dir="/usr/local/share/ca-certificates/caelicode"

    # Export Windows root certs via PowerShell
    local cert_pem
    # shellcheck disable=SC2016  # Single quotes intentional: PowerShell Cert:\ path
    cert_pem="$(/mnt/c/windows/system32/windowspowershell/v1.0/powershell.exe \
        -NoProfile -NonInteractive -Command \
        'Get-ChildItem -Path Cert:\LocalMachine\Root | ForEach-Object { [System.Convert]::ToBase64String($_.RawData) }' \
        2>/dev/null | tr -d '\r' || true)"

    if [ -n "$cert_pem" ]; then
        mkdir -p "$linux_cert_dir"
        local cert_file="${linux_cert_dir}/windows-root-cas.crt"
        : > "$cert_file"
        while IFS= read -r b64; do
            [ -z "$b64" ] && continue
            {
                echo "-----BEGIN CERTIFICATE-----"
                echo "$b64" | fold -w 64
                echo "-----END CERTIFICATE-----"
            } >> "$cert_file"
        done <<< "$cert_pem"
        update-ca-certificates 2>/dev/null || true
        log "Merged Windows root CA certificates into Linux trust store"
    else
        log "No Windows root certificates detected"
    fi
}

# ── Main ─────────────────────────────────────────────────────────────
PROXY_OUTPUT="$(detect_windows_proxy || true)"

if [ -n "$PROXY_OUTPUT" ]; then
    PROXY="$(echo "$PROXY_OUTPUT" | head -1)"
    BYPASS="$(echo "$PROXY_OUTPUT" | tail -1)"
    write_proxy_env "$PROXY" "$BYPASS"
else
    clear_proxy_env
fi

# Merge CA certs if configured
if [ -f /etc/caelicode/config.yaml ]; then
    MERGE_CA="$(grep "merge_ca_certs:" /etc/caelicode/config.yaml 2>/dev/null | grep -c "true" || true)"
    if [ "$MERGE_CA" -gt 0 ]; then
        merge_windows_certs
    fi
fi
